# Generated by Django 2.0.2 on 2018-12-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentries',
            name='datetimeofentry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
