# Generated by Django 2.0.2 on 2018-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181206_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentries',
            name='blogimage',
            field=models.ImageField(default='default.png', upload_to='myimages'),
            preserve_default=False,
        ),
    ]
