# Generated by Django 2.0.2 on 2018-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogentries_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentries',
            name='blogimage',
            field=models.ImageField(null=True, upload_to='myimages'),
        ),
    ]
